### ISSUE TITLE
results

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [bocchilorenzo/CoverScape#22]
hello there!tell me please this is for searching music from Deezer?if yes,I am begging you could you increase unlimited results?it would be great!I know deezer shows few results!please man!!!

**Comment by bocchilorenzo** [comment]
Hi, this is not for searching music but only album covers. It currently has no limit in how many covers are showed, you just scroll and it loads other covers at the end. I'm having some issues with the lastfm and reddit apis, so their sections don't work, but everything else does.

**Comment by KENPOKASMMA1982** [comment]
tell me please something mate!I know that deezer increase limit 300 results for every album...do you think you can appear with some way unlimited????

**Comment by bocchilorenzo** [comment]
I'm not sure what you mean. The deezer API has unlimited access and gives you all the results available for a single album. They only stop when there are no more results or you exceeded 50 requests in under 5 seconds.

**Comment by KENPOKASMMA1982** [comment]
mate I mean that deezer api permit only 300 results maximum for every album and song!thats why I ask you if you can increase unlimited with some way!deezer says that has 60-70 millions songs and appear maximum 300 results!its not fair dude!!!

**Comment by bocchilorenzo** [comment]
Can't really do anything since that limit is server side.
