### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [bocchilorenzo/CoverScape#26]
hello there!manyyyyy congratulations but please could you increase unlimited results?it would be perfect!

I found a way to query more records. There is a parameter called offset, which is not mentioned in API documentation.

https://itunes.apple.com/search?term=a&offset=25&limit=25

https://stackoverflow.com/questions/44177089/itunes-search-api-page-number-for-the-query?fbclid=IwAR3ywf5P6k5zdS_NpSmD9hMedPwCeVomEUldfgKsCJ5DJqu77k_Eyvp6yBA ....also it would be great if you make it increase and songs!

**Comment by bocchilorenzo** [comment]
Added. Now it updates the offset when it reaches the end of the current result stack

**Comment by KENPOKASMMA1982** [comment]
WOOWWWWWWWWWWW GOD BLESS YOU MY FRIEND!!!BUT PLEASE I AM BEGGING YOU COULD YOU MAKE YOUR AMAZINGGGGGGGGGGGGGGG WEB INCREASE AND SONGS?PLEASEEEEEEEEEE MAN....AND BELIEVE ME IT WOULD BE GREAT ALSO IF YOU MAKE IT INCREASE MUSIC BY DATE!FOR EXAMPLE LOVE 2022 AND APPEAR ALL THE ALBUMS AND THE SONGS WHERE RELEASED 2022!  <3

**Comment by KENPOKASMMA1982** [comment]
and please help me how can I run it?I try npm install,npm run dev,npm run serve,npm start...and the same with yarn...but I cant run it!!!

**Comment by bocchilorenzo** [comment]
The number of albums that get visualized upon search is 25 to avoid using too much bandwidth and I don't plan to increase it since you can get other results by simply scrolling down if needed. To run it, you have to install the dependencies with 'npm i --legacy-peer-deps' because the project is made in vue 2. Then just run it with 'npm run serve'.

**Comment by bocchilorenzo** [comment]
Also regarding the search by date, I don't have plans to add more things to this project right now, but maybe in the future I can think about it. Closing since the original issue is solved.

**Comment by KENPOKASMMA1982** [comment]
my friend understand and respect you!just please can you make your amazing web appear and songs?please dude!!!
